name: stock_module
description: "Pacote de estoque (stock_module) — estrutura domain/data/DI alinhada ao sale_module."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.5.3
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  componentes_lr:
    path: C:\Repository\Flutter_X_Components_Flutter

  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/svgs/
